---
name: benchmark
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: publish benchmark history
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: 1.25.x
      - name: Run benchmarks
        run: go test -run=^$ -bench=BenchmarkScrapeAndExport -benchmem ./... | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@a7bc2366eda11037936ea57d811a43b3418d3073 # v1.21.0
        with:
          name: OpenTelemetry Collector Bridge Benchmarks
          tool: go
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
          auto-push: true
          summary-always: true
